FROM node:8.15.1
MAINTAINER Felipe Guerra <felipeguerraoliveira@protonmail.com>

RUN apt-get install -y git

#Criar estrutura do projeto e baixar código-fonte

RUN mkdir -p /app/twitter-backend-consumer

WORKDIR /app/twitter-backend-consumer

RUN git clone https://github.com/felipeguerra19/twitter-backend-consume .

#Instalar bibliotecas
RUN npm install

#Testing chmod +x test.sh && sh test.sh
#RUN npm test

RUN chmod +x start-up.sh

ENV DYNAMODB_ENDPOINT="http://localhost:8000"

CMD ["node", "./src/api/TwitterApi.js"]
